name: adoscope-reusable-build

on:
  workflow_call:
    inputs:
      buildVersion:
        required: true
        type: string
      dotnetVersion:
        required: true
        type: string

env:
  NuGetDirectoryWin: ${{ github.workspace}}\nuget

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnetVersion }}

      - name: Restore Dependencies
        working-directory: .
        run: dotnet restore

      - name: Build
        working-directory: .
        run: dotnet build --no-restore --configuration Release

      - name: Package
        working-directory: .
        run: dotnet pack --no-restore --configuration Release --output ${{ env.NuGetDirectoryWin }}

      - name: Upload Nuget Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Promethix.Framework.Ado.NuGet.${{ inputs.buildVersion }}
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectoryWin }}\*.nupkg