name: adoscope-nuget-publish
on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'NuGet package version to approve'
        required: true
        default: '1.0.0'

env:
  NuGetDirectory: ${{ github.workspace}}/nuget
  NuGetDirectoryWin: ${{ github.workspace}}\nuget

jobs:
  publish:
    name: Publish Promethix.Framework.Ado
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        name: Promethix.Framework.Ado.NuGet.${{ inputs.package_version }}
        github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
        workflow: adoscope-nuget-build.yaml
        path: ${{ env.NuGetDirectory }}
        search_artifacts: true

    - name: Publish Nuget Package Promethix.Framework.Ado
      working-directory: .
      run: |
        echo Directory List
        ls
        echo NuGet Directory List
        ls ${{ env.NuGetDirectory }}
        PACKAGE_VERSION=${{ inputs.package_version }}
        dotnet nuget push ${{ env.NuGetDirectory }}/Promethix.Framework.Ado.${PACKAGE_VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}