name: adoscope-nuget-build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setting up build version
      run: echo "BuildVersion=${{ vars.MAJOR }}.${{ vars.MINOR }}.${{ vars.REVISION }}-alpha" >> $GITHUB_ENV
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      working-directory: .
      run: dotnet restore

    - name: Build
      working-directory: .
      run: dotnet build --no-restore

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore NuGet packages
      working-directory: ./Promethix.Framework.Ado.Tests
      run: dotnet restore

    - name: Run Tests
      working-directory: ./Promethix.Framework.Ado.Tests
      run: dotnet test --no-restore --verbosity normal
